apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
  labels:
    app: gateway-api
    group: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api    # indicates which Pods (with which labeles) need be handled by this Deployment
  template:
    metadata:         # indicates the metadata that will be added to each Pod
      labels:
        app: gateway-api
        group: db
    spec:
      containers:     # defines a running container inside the Pod
        - name: gateway-api
          image: matzpersson/fleetmetrics-api:<VERSION>
          imagePullPolicy: Always
          env:
            - name: MONGO_PORT
              value: "<MONGO_PORT>"
            - name: MONGO_SERVER
              value: <MONGO_SERVER>
            - name: MONGO_DATABASE
              value: <MONGO_DATABASE>
            - name: API_PORT
              value: "<API_PORT>"
            - name: LOGIN_SECRET
              value: <LOGIN_SECRET>
            - name: SMTP_HOST
              value: <SMTP_HOST>
            - name: SMTP_UID
              value: <SMTP_UID>
            - name: SMTP_PWD
              value: <SMTP_PWD>
            - name: MQTT_PORT
              value: <MQTT_PORT>
          ports:
            - containerPort: 8081
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8081
          #     httpHeaders:
          #     - name: Custom-Header
          #       value: Awesome
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
